[package]
name = "mygpt"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17", features = ["wgpu", "train", "vision"] }

async-stream = "0.3"

futures-core = "0.3"
futures-util = "0.3"

tokio = { version = "1", features = ["full"] }

rand = "0.9"
